### ISSUE TITLE
Products Cart page

### ISSUE THREAD

**Issue by Chovv** [julietrinh1/soen341#7]
Creating a page with all the products that were selected prior to entering the page, and that displays the subtotal (+tax, shipping fees).

USERS should be able to:
- Adjust the quantity of each product
- Remove a product entirely from the cart

Acceptance Tests:

- [ ] Total price should reflect sum of all products
- [ ]  Adding/removing an item from shopping cart should change total price
- [ ]  Removing item from shopping cart should increase "quantity available" on sellers page
- [ ] Adding item from shopping cart should decrease "quantity available" on sellers page
- [ ]  Should not be able to have negative quantities in shopping cart
- [ ] Clicking payment button should redirect to another page

**Comment by julietrinh1** [comment]
I believe that this issue should be part of sprint 2

**Comment by kalsij** [comment]
Fuck You
